# Assignment – TensorFlow

## 1. Import TensorFlow and Display Version

In [5]:
!pip install tensorflow

In [60]:
import tensorflow as tf
print(tf.__version__)

2.21.0


## 2. Check Available Devices

In [61]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

## 3. Create Integer Constant

In [59]:
a = tf.constant(25)
a

<tf.Tensor: shape=(), dtype=int32, numpy=25>

## 4. Create Float Constant

In [9]:
b = tf.constant(15.75)
b

<tf.Tensor: shape=(), dtype=float32, numpy=15.75>

## 5. Create String Constant

In [10]:
country = tf.constant("Canada")
country

<tf.Tensor: shape=(), dtype=string, numpy=b'Canada'>

## 6. Create 1D Tensor

In [11]:
numbers = tf.constant([10,20,30,40,50])
numbers

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50], dtype=int32)>

## 7. Convert NumPy Array to Tensor

In [12]:
import numpy as np
arr = np.array([[7,8,9],[10,11,12]])
tf.constant(arr)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

## 8. Create 2D Tensor

In [13]:
tensor_2d = tf.constant([[5,6],[7,8]])
tensor_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>

## 9. Create 1D Tensor

In [14]:
tensor_1d = tf.constant([11,22,33,44])
tensor_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 22, 33, 44], dtype=int32)>

## 10. Create Tensor Using Shape

In [15]:
tensor_shape = tf.constant([2,4,6,8], shape=(2,2), dtype="int32")
tensor_shape

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

## 11. Create 3D Tensor

In [16]:
tensor_3d = tf.constant([[[2,4],[6,8]],[[1,3],[5,7]]], dtype="float32")
tensor_3d

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[2., 4.],
        [6., 8.]],

       [[1., 3.],
        [5., 7.]]], dtype=float32)>

## 12. Display Tensor Type

In [17]:
type(tensor_3d)

tensorflow.python.framework.ops.EagerTensor

## 13. Display Tensor Shape

In [18]:
tensor_3d.shape

TensorShape([2, 2, 2])

## 14. Create Variable

In [19]:
tf.Variable(10)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

## 15. Variable with List

In [20]:
x = tf.Variable([5,10,15,20])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 5, 10, 15, 20], dtype=int32)>

## 16. Variable Name

In [21]:
x.name

'Variable:0'

## 17. Variable Shape

In [22]:
x.shape

TensorShape([4])

## 18. Variable Datatype

In [23]:
x.dtype

tf.int32

## 19. Float Variable

In [24]:
y = tf.Variable([2.5,4.5,6.5])
y

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2.5, 4.5, 6.5], dtype=float32)>

## 20. Boolean Variable

In [25]:
flag = tf.Variable([True,False,True])
flag

<tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([ True, False,  True])>

## 21. Convert Constant to Variable

In [26]:
const_tensor = tf.constant([9,8,7,6])
tf.Variable(const_tensor)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([9, 8, 7, 6], dtype=int32)>

## 22. Create 2D Variable

In [27]:
matrix = tf.Variable([[10,20],[30,40]])
matrix

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

## 23. Reshape Variable

In [28]:
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

## 24. Find Largest Value Index

In [29]:
tf.argmax(matrix)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

## 25. Convert to Tensor

In [30]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 10, 15, 20], dtype=int32)>

## 26. Convert to Tensor

In [31]:
tf.convert_to_tensor(matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

## 27. Updating Variables

In [32]:
x = tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

## 28. Assign

In [33]:
x.assign([8,7,6,5])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([8, 7, 6, 5], dtype=int32)>

## 29. Assign

In [34]:
x.assign([9,8,7,6])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([9, 8, 7, 6], dtype=int32)>

## 30. Assign Add

In [35]:
x.assign_add([1,1,1,1])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10,  9,  8,  7], dtype=int32)>

## 31. Addition

In [36]:
tf.add(40,60)

<tf.Tensor: shape=(), dtype=int32, numpy=100>

## 32. Add Lists

In [37]:
l1=[2,4,6,8]
l2=[1,3,5,7]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  7, 11, 15], dtype=int32)>

## 33. Add Tuples

In [38]:
t1=(5,10,15)
t2=(2,4,6)
tf.add(t1,t2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 14, 21], dtype=int32)>

## 34. Scalar Addition

In [39]:
tf.add([10,20,30],5)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 25, 35], dtype=int32)>

## 35. Absolute Value

In [40]:
x=tf.constant([-4.5,2.5])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 2.5], dtype=float32)>

## 36. Subtraction

In [41]:
tf.subtract([20,30,40],5)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 25, 35], dtype=int32)>

## 37. Multiplication

In [42]:
x=tf.constant([2,3,4])
tf.multiply(x,x)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  9, 16], dtype=int32)>

## 38. Maximum

In [43]:
a=tf.constant([2,6,8])
b=tf.constant([4,5,7])
tf.math.maximum(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 8], dtype=int32)>

## 39. Minimum

In [44]:
tf.math.minimum(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 7], dtype=int32)>

## 40. Logarithm

In [45]:
x=tf.constant([1.0,2.0,8.0])
tf.math.log(x)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.       , 0.6931472, 2.0794415], dtype=float32)>

## 41. Division

In [46]:
a=tf.constant([20,40,60])
b=tf.constant([2,4,5])
tf.divide(a,b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([10., 10., 12.])>

## 42. Power

In [47]:
x=tf.constant([2,3,4])
tf.pow(x,2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  9, 16], dtype=int32)>

## 43. Square Root

In [48]:
x=tf.constant([25.0,81.0])
tf.sqrt(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 9.], dtype=float32)>

## 44. Ones

In [49]:
tf.ones(5)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)>

## 45. Ones Matrix

In [50]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## 46. Ones 3D

In [51]:
tf.ones((2,3,2))

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

## 47. Zeros

In [52]:
tf.zeros(4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

## 48. Zeros Integer

In [53]:
tf.zeros((3,3),dtype=tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

## 49. Ones Like

In [54]:
sample=tf.constant([[1,2],[3,4]])
tf.ones_like(sample)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

## 50. Zeros Like

In [55]:
tf.zeros_like(sample)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

## 51. Sparse Tensor

In [56]:
sparse_tensor=tf.SparseTensor(indices=[[0,1],[1,0]], values=[100,200], dense_shape=[3,4])
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]], shape=(2, 2), dtype=int64), values=tf.Tensor([100 200], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

## 52. Convert Sparse to Dense

In [57]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  0, 100,   0,   0],
       [200,   0,   0,   0],
       [  0,   0,   0,   0]], dtype=int32)>