# PyTorch Tensor Assignment 

In [1]:
!pip install torch

   ---------------------------------------- 0.0/123.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/123.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/123.0 MB 2.8 MB/s eta 0:00:44
    --------------------------------------- 2.1/123.0 MB 3.6 MB/s eta 0:00:34
   - -------------------------------------- 3.1/123.0 MB 4.1 MB/s eta 0:00:30
   - -------------------------------------- 3.9/123.0 MB 3.9 MB/s eta 0:00:31
   - -------------------------------------- 4.7/123.0 MB 4.1 MB/s eta 0:00:29
   - -------------------------------------- 6.0/123.0 MB 4.2 MB/s eta 0:00:28
   -- ------------------------------------- 7.1/123.0 MB 4.3 MB/s eta 0:00:27
   -- ------------------------------------- 8.4/123.0 MB 4.5 MB/s eta 0:00:26
   --- ------------------------------------ 9.4/123.0 MB 4.6 MB/s eta 0:00:25
   --- ------------------------------------ 10.7/123.0 MB 4.7 MB/s eta 0:00:24
   --- ------------------------------------ 12.1/123.0 MB 4.8 MB/s eta 0:00:2

In [2]:
import torch
print(torch.__version__)

2.12.0+cpu


In [3]:
print('CUDA Available:', torch.cuda.is_available())

CUDA Available: False


## Creating Tensors

In [4]:
# empty tensor
x = torch.empty(3,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
# zeros tensor
torch.zeros(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
# ones tensor
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# random tensor
torch.rand(5,2)

tensor([[0.3134, 0.9887],
        [0.3100, 0.9265],
        [0.1892, 0.9693],
        [0.9534, 0.9993],
        [0.3141, 0.1812]])

In [8]:
torch.manual_seed(123)
torch.rand(3,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]])

In [9]:
torch.tensor([[10,20],[30,40]])

tensor([[10, 20],
        [30, 40]])

In [10]:
print(torch.arange(1,16,3))
print(torch.linspace(0,20,5))
print(torch.eye(4))

tensor([ 1,  4,  7, 10, 13])
tensor([ 0.,  5., 10., 15., 20.])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


## Tensor Data Types

In [11]:
a = torch.tensor([5,10,15])
a.dtype

torch.int64

In [12]:
torch.tensor([2,4,6], dtype=torch.float64)

tensor([2., 4., 6.], dtype=torch.float64)

In [13]:
a.to(torch.float32)

tensor([ 5., 10., 15.])

## Mathematical Operations

### 1. Scalar Operations

In [14]:
x = torch.rand(2,2)
x

tensor([[0.7264, 0.3153],
        [0.6871, 0.0756]])

In [15]:
x+5
x-1
x*4
x/2
x**3

tensor([[0.3834, 0.0313],
        [0.3244, 0.0004]])

### 2. Element Wise Operations

In [16]:
a=torch.rand(2,2)
b=torch.rand(2,2)
print(a)
print(b)

tensor([[0.1966, 0.3164],
        [0.4017, 0.1186]])
tensor([[0.8274, 0.3821],
        [0.6605, 0.8536]])


In [17]:
a+b
a-b
a*b
a/b

tensor([[0.2377, 0.8281],
        [0.6082, 0.1389]])

In [18]:
c=torch.tensor([-5,3,-8,10])
torch.abs(c)

tensor([ 5,  3,  8, 10])

In [19]:
d=torch.tensor([1.2,4.8,6.1,2.9])
torch.round(d)

tensor([1., 5., 6., 3.])

In [20]:
torch.ceil(d)
torch.floor(d)
torch.clamp(d,min=2,max=5)

tensor([2.0000, 4.8000, 5.0000, 2.9000])

### 3. Reduction Operations

In [21]:
e=torch.randint(1,20,(3,3),dtype=torch.float32)
e

tensor([[16.,  6.,  3.],
        [15.,  1.,  5.],
        [16.,  6., 14.]])

In [22]:
torch.sum(e)
torch.mean(e)
torch.max(e)
torch.min(e)

tensor(1.)

In [23]:
torch.std(e)
torch.var(e)
torch.argmax(e)

tensor(0)

### 4. Matrix Operations

In [24]:
m1=torch.tensor([[1.,2.],[3.,4.]])
m2=torch.tensor([[5.,6.],[7.,8.]])

In [25]:
torch.matmul(m1,m2)

tensor([[19., 22.],
        [43., 50.]])

In [26]:
m1.T

tensor([[1., 3.],
        [2., 4.]])

### 5. Comparison Operations

In [27]:
x=torch.tensor([2,4,6,8])
y=torch.tensor([1,4,7,8])

In [28]:
x==y
x>y
x<y

tensor([False, False,  True, False])

### 6. Special Functions

In [29]:
x=torch.tensor([1.0,2.0,3.0])
torch.sqrt(x)

tensor([1.0000, 1.4142, 1.7321])

In [30]:
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855])

In [31]:
torch.log(x)

tensor([0.0000, 0.6931, 1.0986])

## Inplace Operations

In [32]:
a=torch.tensor([1.,2.,3.])
a.add_(5)
a

tensor([6., 7., 8.])

## Copying a Tensor

In [33]:
x=torch.tensor([11,22,33])
y=x.clone()
y

tensor([11, 22, 33])